<html>
<head>
    <title>motorbike - create new</title>
</head>
<body>
<div>
    <h2>create new motorbike</h2>
    <form id="form-create-motorbike" method="post" action="/motorbike/store">
        <p>
            <label for="text-name">name</label>
            <br>
            <input id="text-name" type="text" name="name">
        </p>
        <p>
            <label for="text-model">model</label>
            <br>
            <input id="text-model" type="text" name="model">
        </p>
        <p>
            <label for="select-color">color</label>
            <br>
            <select id="select-color" name="color">
                <option>red</option>
                <option>blue</option>
                <option>green</option>
                <option>black</option>
                <option>gray</option>
            </select>
        </p>
        <p>
            <label for="number-weight">weight</label>
            <br>
            <input id="number-weight" type="number" name="weight">
        </p>
        <p>
            <label for="number-price">price</label>
            <br>
            <input id="number-price" type="number" name="price">
        </p>
        <p>
            <button type="submit">create</button>
            <button type="reset">reset</button>
        </p>
    </form>
</div>
</body>
</html>